version: 2
jobs:
  verify-changelog:
    docker:
      - image: ponylang/changelog-tool:release
    steps:
      - checkout
      - run: changelog-tool verify

  release-vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: make test config=release ci=true

  release-vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: make test config=release ci=true

  debug-vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: make test config=debug ci=true

  debug-vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: make test config=debug ci=true
      

workflows:
  version: 2
  commit:
    jobs:
      - verify-changelog
      - release-vs-ponyc-release
      - debug-vs-ponyc-release

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - release-vs-ponyc-master
      - debug-vs-ponyc-master
